Traceback (most recent call last):
  File "/Users/boris/miniconda3/envs/tmp1/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/boris/miniconda3/envs/tmp1/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/boris/miniconda3/envs/tmp1/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/boris/miniconda3/envs/tmp1/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/boris/miniconda3/envs/tmp1/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/boris/miniconda3/envs/tmp1/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/boris/miniconda3/envs/tmp1/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
word_list = open('words.txt').read().split()

db = shelve.open('anagram_map', 'n')
for word in word_list:
    add_word(word, db)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[77], line 5[0m
[1;32m      3[0m db [38;5;241m=[39m shelve[38;5;241m.[39mopen([38;5;124m'[39m[38;5;124managram_map[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mn[39m[38;5;124m'[39m)
[1;32m      4[0m [38;5;28;01mfor[39;00m word [38;5;129;01min[39;00m word_list:
[0;32m----> 5[0m     [43madd_word[49m(word, db)
        db [0;34m= <shelve.DbfilenameShelf object at 0x104abc910>[0m[0;34m
        [0mword [0;34m= 'aa'[0m

[0;31mNameError[0m: name 'add_word' is not defined

